import Head from "next/head";
import { useEffect, useState } from "react";
import QuerySection from "./QuerySection";
import Content from "./Content";
import { DictionaryData } from "./DictionaryInterfaces";

export default function Home() {
  const [font, setFont] = useState<string>("font-sans");
  const [userWord, setUserWord] = useState<string>("");
  const [dictData, setDictData] = useState<DictionaryData>({
    word: "",
    phonetic: "",
    phonetics: [{}],
    origin: "",
    meanings: [{}]
  });
  // const [dictData, setDictData] = useState<Array<DictionaryData>>([{
  //   word: "",
  //   phonetics: Array<Phonetics>{text:"", audio:""},
  //   origin: "",
  //   meanings: [],
  // }]);

  //Handle page font
  useEffect(() => {
    document.body.style.fontFamily = font;
  }, [font]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="public/favicon-32x32.png" /> */}
      </Head>
      <main className="flex w-11/12 h-fit mx-auto justify-center flex-col" id="Content-container">
        <QuerySection
          font={font}
          setFont={setFont}
          userWord={userWord}
          setUserWord={setUserWord}
          dictData={dictData}
          setDictData={setDictData}
        />
        <Content 
        dictData={dictData}
        userWord={userWord}
        />
      </main>
    </>
  );
}
