import Head from "next/head";
import { useEffect, useState } from "react";
import QuerySection from "./QuerySection";
import Content from "./Content";

export default function Home() {
  const [font, setFont] = useState<string>("font-sans")
  const [userWord, setUserWord] = useState<string>("hllo");
  const [dictData, setDictData] = useState<any>("");
  const [word, setWord] = useState<string>("");

  //Handle page font
  useEffect(() => {
    document.body.style.fontFamily = font;
  }, [font])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="public/favicon-32x32.png" /> */}
      </Head>
      <main className="flex bg-red-600 w-11/12 h-fit mx-auto justify-center flex-col bg-gray-500">
        <QuerySection
          font={font}
          setFont={setFont}
          userWord={userWord}
          setUserWord={setUserWord}
          dictData={dictData}
          setDictData={setDictData}
          word={word}
          setWord={setWord}
        />
        <Content />
      </main>
    </>
  );
}
