import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import GetWordInfo from "./getWord";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [userWord, setWord] = useState<string>("hello");
  const [inputValue, setInputValue] = useState<string>("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="public/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
        <input
          className="input-box"
          id="word-entry"
          onChange={(e) => {
            setInputValue(e.target.value);
          }}
          value={inputValue}
        />
        <h1>{inputValue}</h1>
        <GetWordInfo userWord={userWord} />
      </main>
    </>
  );
}
